In [2]:
import numpy as np


In [2]:
sales = [1,2]
sales_array = np.array(sales)
sales_array

array([1, 2])

In [3]:
np.ndim(sales_array)

1

In [11]:
sales = [[1,2,3],[3,5,7]]
sales_array = np.array(sales)
print(sales_array.shape)
print(sales_array.ndim)
print(sales_array.T)
print(sales_array.dtype)


(2, 3)
2
[[1 3]
 [2 5]
 [3 7]]
int32


In [18]:
wonz = np.ones((1,3),dtype=int)
wonz.dtype
wonz

array([[1, 1, 1]])